repos:
    - repo: https://github.com/pycqa/isort
      rev: 5.7.0
      hooks:
          - id: isort
            types: [text]
            types_or: [python, cython]
            args: ["--profile", "black"]
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.4.0
      hooks:
          - id: check-docstring-first
          - id: check-executables-have-shebangs
          - id: check-merge-conflict
          - id: check-toml
          - id: end-of-file-fixer
          - id: mixed-line-ending
            args: [--fix=lf]
          - id: requirements-txt-fixer
          - id: trailing-whitespace
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.8.4
      hooks:
          - id: flake8
    - repo: https://github.com/ambv/black
      rev: 20.8b1
      hooks:
          - id: black
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.790
      hooks:
          - id: mypy
