[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "setuptools-scm"]

[project]
authors = [{email = "test@gmail.com", name = ""}]
classifiers = ["Programming Language :: Python :: 3"]
dependencies = []
description = ""
keywords = []
license = {text = "BSD-3-Clause"}
name = "template"
readme = "README.md"
requires-python = "~=3.10"
version = "0.0.1"

[project.optional-dependencies]
dev = [
  "black",
  "mypy",
  "pre-commit",
  "tox",
]

[tool.isort]
profile = "black"

[tool.mypy]
plugins = ["numpy.typing.mypy_plugin", "pydantic.mypy"]

[tool.pytest.ini_options]
addopts = "--color=yes -v"

[tool.ruff]
fix = true
force-exclude = true
select = [
  # flake8-bugbear
  "B",
  # pycodestyle
  "E",
  # pyflakes
  "F",
  # isort
  "I",
  # pylint
  "PLE",
  "PLR",
  "PLW",
  # flake8-quotes
  "Q",
  "W",
  # flake8-2020
  "YTT",
]

[tool.ruff.mccabe]
max-complexity = 18

[tool.tomlsort]
all = true
trailing_comma_inline_array = true

[tool.tox]
legacy_tox_ini = """
    [gh-actions]
    python =
        3.10: py310

    [testenv]
    commands =
        pytest \
        --cov=.
    deps =
        pytest
        pytest-cov

    [tox]
    env_list =
        py310
"""
