[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "setuptools-scm"]

[tool.isort]
profile = "black"

[tool.mypy]
plugins = "numpy.typing.mypy_plugin"

[tool.ruff]
fix = true
force-exclude = true
ignore = ["E741", "W605"]
select = [
  # flake8-bugbear
  "B",
  # pycodestyle
  "E",
  # pyflakes
  "F",
  # pylint
  "PLE",
  "PLR",
  "PLW",
  # flake8-quotes
  "Q",
  "W",
  # flake8-2020
  "YTT",
]

[tool.ruff.mccabe]
max-complexity = 18

[tool.tomlsort]
all = true
trailing_comma_inline_array = true
