[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools",
    "setuptools-scm",
]

[project]
authors = [
    {email = "test@gmail.com", name = ""},
]
classifiers = [
    "License :: OSI Approved :: BSD License",
    "Operating System :: POSIX",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Typing :: Typed",
]
dependencies = []
description = ""
dynamic = [
    "version",
]
keywords = []
name = "example"
readme = "README.md"
requires-python = ">=3.8"
license.file = "LICENSE.md"
optional-dependencies.dev = [
    "black",
    "build",
    "mypy",
    "pre-commit",
    "ruff",
    "tox",
    "twine",
]
optional-dependencies.docs = [
    "pdoc3",
]
optional-dependencies.readme = [
    "pytest-codeblocks",
]
urls.Code = "https://github.com/paddyroddy/python-template"
urls.Documentation = "https://paddyroddy.github.io/python-template/"
urls.Homepage = "https://github.com/paddyroddy/python-template"
urls.Issues = "https://github.com/paddyroddy/python-template/issues"

[tool.coverage]
report = {skip_covered = true, sort = "cover"}
run = {branch = true, parallel = true, source = ["example"]}
paths.source = [
    "src",
    ".tox*/*/lib/python*/site-packages",
]

[tool.mypy]
explicit_package_bases = true
plugins = [
    "numpy.typing.mypy_plugin",
    "pydantic.mypy",
]

[tool.pytest.ini_options]
addopts = "--color=yes -v"
testpaths = [
    "tests",
]

[tool.ruff]
fix = true
force-exclude = true
ignore = [
    "D203",
    "D213",
]
per-file-ignores = {"__init__.py" = [
    "D205",
], "test_*" = [
    "S101",
]}
select = [
    "A",
    "ANN",
    "ARG",
    "B",
    "BLE",
    "C",
    "COM",
    "D",
    "DJ",
    "DTZ",
    "E",
    "EM",
    "ERA",
    "EXE",
    "F",
    "FBT",
    "G",
    "I",
    "ICN",
    "INP",
    "ISC",
    "N",
    "NPY",
    "PD",
    "PGH",
    "PIE",
    "PL",
    "PT",
    "PTH",
    "PYI",
    "Q",
    "RET",
    "RSE",
    "RUF",
    "S",
    "SIM",
    "SLF",
    "T",
    "TCH",
    "TID",
    "TRY",
    "UP",
    "W",
]
target-version = "py38"
isort.known-first-party = ["example"]
mccabe.max-complexity = 18
pep8-naming.classmethod-decorators = [
    "classmethod",
    "pydantic.validator",
]

[tool.setuptools_scm]
local_scheme = "no-local-version"
write_to = "src/example/_version.py"

[tool.tomlsort]
all = true
spaces_indent_inline_array = 4
trailing_comma_inline_array = true
overrides."project.classifiers".inline_arrays = false
overrides."tool.coverage.paths.source".inline_arrays = false

[tool.tox]
legacy_tox_ini = """
    [gh-actions]
    python =
        3.8: py38
        3.9: py39
        3.10: py310

    [testenv]
    commands =
        pytest --cov --slow
    deps =
        pytest-cov
        pytest-skip-slow

    [tox]
    env_list =
        py3{8,9,10}
"""
