---
name: Add issues to project board

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  add-issue-to-project:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/add-to-project@c5e8a3f7655f658e2af4e203482fd0996da6b9fe # v0
        with:
          project-token: ${{ secrets.PROJECT_PAT }}
