name: Tests

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout source
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9

            - name: restore python cache
              uses: actions/cache@v2
              with:
                  path: ${{ env.pythonLocation }}
                  key: ${{ hashFiles('requirements.txt') }}

            - name: Install dependencies
              run: pip install -r requirements.txt

            - name: Run tests
              run: pytest --color=yes -v
