name: Deploy

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: paddyroddy/.github/actions/python/deployment@v0.2.0
        with:
          pypi-api-token: ${{ secrets.PYPI_API_TOKEN }}
          pyproject-toml: ./pyproject.toml
          test-pypi-api-token: ${{ secrets.TEST_PYPI_API_TOKEN }}
