name: Deploy

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: paddyroddy/.github/actions/python/deployment@cbc478d97e23dbb3ed95725817be6d84cef12b6c # v0
        with:
          pypi-api-token: ${{ secrets.PYPI_API_TOKEN }}
          pyproject-toml: ./pyproject.toml
          python-version: "3.12"
          test-pypi-api-token: ${{ secrets.TEST_PYPI_API_TOKEN }}
