name: tests

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout source
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9

            - name: set PY
              run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV

            - name: cache stuff
              uses: actions/cache@v2
              with:
                path: |
                  ${{ env.pythonLocation }}
                key: |
                  pytest-${{ env.PY }}

            - name: Install dependencies
              run: pip install pytest

            - name: Run tests
              run: pytest --color=yes -v
