name: Deploy

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: paddyroddy/.github/actions/python/deployment@c94ef1b770833731e8b7b82ffda36d14840554a4 # v0
        with:
          pypi-api-token: ${{ secrets.PYPI_API_TOKEN }}
          pyproject-toml: ./pyproject.toml
          python-version: "3.12"
          test-pypi-api-token: ${{ secrets.TEST_PYPI_API_TOKEN }}
