---
name: Deploy

on:
  push:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/python/deployment@e59369bbd745ef1eae9b8327fba32a4f87ff13ca # v0
        with:
          pyproject-toml: ./pyproject.toml
          python-version: "3.12"
