---
name: Deploy

# yamllint disable-line rule:truthy
on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/python/deployment@37294f6997fb9f62afa155f09808dc3c34459fb2 # v0
        with:
          pyproject-toml: ./pyproject.toml
          python-version: "3.12"
