name: Deploy

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: paddyroddy/.github/actions/python/deployment@34e390ddee5772749fb85130dc096071b690a7b7 # v0
        with:
          pypi-api-token: ${{ secrets.PYPI_API_TOKEN }}
          pyproject-toml: ./pyproject.toml
          python-version: "3.12"
          test-pypi-api-token: ${{ secrets.TEST_PYPI_API_TOKEN }}
