---
name: Deploy

on:
  push:
    branches:
      - main
      - renovate/**
    tags:
      - v*
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/python/deployment@df30b54c0cb391185a5931a393efb76d8d0f7789 # v0
        with:
          pyproject-toml: ./pyproject.toml
          python-version: "3.12"
