---
name: Deploy

on:
  push:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/python/deployment@6945dc7543c02201ffb88ace2286439798acbda8 # v0
        with:
          pyproject-toml: ./pyproject.toml
          python-version: "3.12"
