---
name: Deploy

on:
  push:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/python/deployment@69431c4ec1e375c5fe5f8fa96ae1e05f371d8326 # v0
        with:
          pyproject-toml: ./pyproject.toml
          python-version: "3.12"
