---
name: Documentation

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/python/pdoc@c2013abbbd54e9ea46017879588e2e915afd087c # v0
        with:
          docs-dependency-section: .[docs]
          gh-pages-publish-directory: ./html/example
          github-token: ${{ secrets.GITHUB_TOKEN }}
          project-directory: ./src/example
          pyproject-toml: ./pyproject.toml
          python-version: "3.12"
          template-directory: ./documentation
