name: Documentation

on:
  push:
    branches:
      - main

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: paddyroddy/.github/actions/python/pdoc@0860bb5de5029a6ef6adbd1da9655eafc9c8231f # v0
        with:
          docs-dependency-section: .[docs]
          gh-pages-publish-directory: ./html/example
          github-token: ${{ secrets.GITHUB_TOKEN }}
          project-directory: ./src/example
          pyproject-toml: ./pyproject.toml
          python-version: "3.12"
          template-directory: ./documentation
