---
name: Documentation

on:
  push:
    branches:
      - main

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/python/pdoc@6945dc7543c02201ffb88ace2286439798acbda8 # v0
        with:
          docs-dependency-section: .[docs]
          gh-pages-publish-directory: ./html/example
          github-token: ${{ secrets.GITHUB_TOKEN }}
          project-directory: ./src/example
          pyproject-toml: ./pyproject.toml
          python-version: "3.12"
          template-directory: ./documentation
