name: Documentation

on:
  push:
    branches:
      - main

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: paddyroddy/.github/actions/python/pdoc@v0.2.0
        with:
          docs-dependency-section: .[docs]
          gh-pages-publish-directory: ./html/sleplet
          project-directory: ./src/sleplet
          pyproject-toml: ./pyproject.toml
          template-directory: ./documentation
