name: Examples

on:
  workflow_dispatch:

jobs:
  readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "pyproject.toml"

      - name: Cache pooch
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/example
          key: tox-${{ hashFiles('pyproject.toml') }}

      - name: Install dependencies
        run: python -m pip install -e .[readme]

      - name: Run examples in the README
        run: python -m pytest --codeblocks README.md

  examples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "pyproject.toml"

      - name: Cache pooch
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/example
          key: tox-${{ hashFiles('pyproject.toml') }}

      - name: Install dependencies
        run: python -m pip install -e .[docs]

      - name: Run examples in the examples folder
        run: >-
          find examples -name "*.py"
          -exec sh -c 'for f;
          do echo $f;
          python "$f" || exit 1
          ; done' sh {} +
