name: Update Copyright

on:
  schedule:
    - cron: "0 3 1 1 *"

jobs:
  update-license-year:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with:
          fetch-depth: 0

      - uses: FantasticFiasco/action-update-license-year@v3
        with:
          path: LICENCE.md
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr merge --merge --delete-branch
