---
name: Linting

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/linting@c35454fa3ce8fba0c3ea48d623cbfa572716c367 # v0
        with:
          pre-commit-config: ./.pre-commit-config.yaml
