name: Linting

on:
  push:
    branches:
      - main
      - "renovate/**"
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: paddyroddy/.github/actions/linting@a4f050199bd1fbb2d8fceebaa0278517c4992047 # v0.21.0
        with:
          pre-commit-config: ./.pre-commit-config.yaml
