---
name: Test

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  test:
    name: ${{ matrix.os }} py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/python/tox@512a88ef0d35d185588d460030660a184fc2db36 # v0
        with:
          cache-path: |-
            .tox
          operating-system: ${{ matrix.os }}
          pyproject-toml: ./pyproject.toml
          python-version: ${{ matrix.python-version }}
