name: Test

on:
  push:
    branches:
      - main
      - "renovate/**"
  pull_request:

jobs:
  test:
    name: ${{ matrix.os }} py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
    steps:
      - uses: paddyroddy/.github/actions/python/tox@909a876d9f25e81524e29bf6463c117d6826855b # v0.20.0
        with:
          cache-path: |-
            .tox
          coverage-with-coveralls: no
          operating-system: ${{ matrix.os }}
          pyproject-toml: ./pyproject.toml
          python-version: ${{ matrix.python-version }}
