---
name: Test

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:
  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: >-
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  test:
    name: ${{ matrix.os }} py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/python/tox@bb1ef2b53f8ed8feef3238ab84ad31aaaa6e947d # v0
        with:
          cache-path: .tox
          operating-system: ${{ matrix.os }}
          pyproject-toml: ./pyproject.toml
          python-version: ${{ matrix.python-version }}
