name: Test

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
      - "renovate/**"
  pull_request:

jobs:
  test:
    name: ${{ matrix.os }} py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/python/tox@2b3c6aedb710b5b43bea7de083eabdb73a408515 # v0
        with:
          cache-path: |-
            .tox
          operating-system: ${{ matrix.os }}
          pyproject-toml: ./pyproject.toml
          python-version: ${{ matrix.python-version }}
